### ISSUE TITLE
Docker container gets shut down after a few seconds

### ISSUE THREAD

**Issue by kunaltyagi** [ofek/hatch-containers#20]
![image](https://github.com/ofek/hatch-containers/assets/2657068/ba922648-743d-4118-a939-85559d42d5e3)
This is quite consistent, in interactive as well as non-interactive mode.

config:
```toml
[tool.hatch.envs.docker]
python = "3.11"
type = "container"
image = "python:{version}-slim"
extra-dependencies = []
features = []
```
